#!/usr/bin/env bash
# Regenerate THIRD_PARTY_LICENSES.md: the license notices of every crate that ends up inside the
# release binary (build-time-only proc-macro crates are left out). For crates offered under a
# choice of licenses, the MIT text is reproduced.
set -euo pipefail
cd "$(dirname "$0")/.."

cargo="${CARGO:-cargo}"
command -v "$cargo" >/dev/null || cargo="$HOME/.cargo/bin/cargo"
registry="${CARGO_HOME:-$HOME/.cargo}/registry/src"
out=THIRD_PARTY_LICENSES.md

crates="$("$cargo" tree --offline --locked --target aarch64-unknown-linux-gnu -e normal,no-proc-macro --prefix none \
    --format '{p}|{l}' | grep -v -e '(proc-macro)' -e '(\*)' -e '^frameeyeosc ' | sort -u)"

{
    echo "# Third-party licenses"
    echo
    echo "The frameeyeosc binary includes the following Rust crates. Their license notices follow."
    echo "It also includes the Rust standard library, licensed under MIT OR Apache-2.0"
    echo "(https://github.com/rust-lang/rust)."
    echo
    echo "This file is generated by scripts/third-party-licenses.sh."
    echo
    while IFS='|' read -r pkg license; do
        name="${pkg%% *}"
        version="${pkg#* v}"
        dir="$(find "$registry" -maxdepth 2 -type d -name "$name-$version" | head -n 1)"
        file=""
        for candidate in LICENSE-MIT LICENSE_MIT LICENSE-MIT.md LICENSE LICENSE.md; do
            if [[ -f "$dir/$candidate" ]]; then file="$dir/$candidate"; break; fi
        done
        if [[ -z "$file" ]]; then
            echo "No license file found for $name $version" >&2
            exit 1
        fi
        echo "## $name $version"
        echo
        echo "License: $license"
        echo
        echo '```'
        sed 's/\r$//' "$file"
        echo '```'
        echo
    done <<<"$crates"
} >"$out"
echo "$out"
