#!/usr/bin/env bash
# Regenerate THIRD_PARTY_LICENSES.md: the license notices of every crate that ends up inside the
# release binary (build-time-only proc-macro crates are left out). For crates offered under a
# choice of licenses, the MIT text is reproduced.
set -euo pipefail
cd "$(dirname "$0")/.."

cargo="${CARGO:-cargo}"
command -v "$cargo" >/dev/null || cargo="$HOME/.cargo/bin/cargo"
rustc="${RUSTC:-rustc}"
command -v "$rustc" >/dev/null || rustc="$HOME/.cargo/bin/rustc"
rust_mit="$("$rustc" --print sysroot)/share/doc/rust/licenses/MIT.txt"
registry="${CARGO_HOME:-$HOME/.cargo}/registry/src"
out=THIRD_PARTY_LICENSES.md

crates="$("$cargo" tree --offline --locked --target aarch64-unknown-linux-gnu -e normal,no-proc-macro --prefix none \
    --format '{p}|{l}' | grep -v -e '(proc-macro)' -e '(\*)' -e '^frameeyeosc ' | sort -u)"

{
    echo "# Third-party licenses"
    echo
    echo "The frameeyeosc binary includes the Rust standard library and the following Rust crates."
    echo "Their license notices follow."
    echo
    echo "This file is generated by scripts/third-party-licenses.sh."
    echo
    while IFS='|' read -r pkg license; do
        name="${pkg%% *}"
        version="${pkg#* v}"
        dir="$(find "$registry" -maxdepth 2 -type d -name "$name-$version" | head -n 1)"
        file=""
        for candidate in LICENSE-MIT LICENSE_MIT LICENSE-MIT.md LICENSE LICENSE.md; do
            if [[ -f "$dir/$candidate" ]]; then file="$dir/$candidate"; break; fi
        done
        if [[ -z "$file" ]]; then
            echo "No license file found for $name $version" >&2
            exit 1
        fi
        echo "## $name $version"
        echo
        echo "License: $license"
        echo
        echo '```'
        sed 's/\r$//' "$file"
        echo '```'
        echo
    done <<<"$crates"
    echo "## Rust standard library"
    echo
    echo "License: MIT OR Apache-2.0. Per-component notices are in the COPYRIGHT file of the Rust"
    echo "project (https://github.com/rust-lang/rust/blob/master/COPYRIGHT)."
    echo
    echo '```'
    sed -e 's/\r$//' -e 's/<year> <copyright holders>/The Rust Project Contributors/' "$rust_mit"
    echo '```'
} >"$out"
echo "$out"
